language: generic

#env:
matrix:
    allow_failures:
        - env: TARGET_SYSTEM=OSX
    include:
        - os: linux
          dist: trusty
          compiler: g++
          sudo: required
          services: docker
          env:
            - TARGET_SYSTEM=Linux
            - # BABL_GIT_TAG=BABL_0_1_52
            - # GEGL_GIT_TAG=GEGL_0_4_4
            - # GIMP_GIT_TAG=GIMP_2_10_4
          before_script:
            - travis_wait 120 sleep infinity & sudo docker pull photoflow/docker-trusty-gimp
            - sudo docker run -it -v $(pwd):/sources -e BABL_GIT_TAG="$BABL_GIT_TAG" -e GEGL_GIT_TAG="$GEGL_GIT_TAG" -e GIMP_GIT_TAG="$GIMP_GIT_TAG" photoflow/docker-trusty-gimp bash /sources/build-appimage.sh
          after_success:
            - cd $TRAVIS_BUILD_DIR
            - ls -lh
            - bash package-appimage.sh
            - ls out/* 
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - bash  ./upload_rotate.sh "continuous" out/* >& /dev/null
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
